name: BAuth-Import
version: ${project.version}
main: ru.baronessdev.free.bauth_addons.bimport.Import
depend: [ BaronessAuth ]
authors: [ Black_Baroness ]
website: https://market.baronessdev.ru/shop/import.6/
